units_files_to_cover:
  - app/models
functionals_files_to_cover:
  - app/controllers
  - app/helpers
units_files_to_test:
  - models
functionals_files_to_test:
  - controllers
  - helpers
before_rcov: db:test:prepare